<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE productos
[
<!ELEMENT productos (producto+)>
<!ELEMENT producto (raton | teclado | monitor)>
<!ELEMENT teclado (codigo+, nombre?, descripcion?)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
]>
<productos>
    <producto>
        <raton>
            <codigo>27A</codigo>
        </raton>
    </producto>
    <producto>
        <teclado>
            <codigo>28D</codigo>
            <descripcion>Teclado en Espa√±ol</descripcion>
        </teclado>
    </producto>
</productos>

