=== angeldzz/PrimerCursoDAW/Lenguaje/3_Trimestre_LM/XML/ejercicioXSD_paises.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="paises">
    <xs:complexType>
      <xs:sequence>
      <xs:element name="pais" maxOccurs="unbounded">
          <xs:complexType>
          <xs:sequence>
            <xs:element name="comida_tipica" type="xs:string" minOccurs="2" maxOccurs="unbounded">
            <xs:complexType>
            <xs:attribute name="tipo"/>
            </xs:complexType> 
            </xs:element>
            <xs:element name="region" type="xs:string" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                <xs:element name="nombre" type="xs:string" maxOccurs="unbounded"/>
                <xs:element name="paisajes" type="xs:string" maxOccurs="unbounded">
                  <xs:complexType>
                  <xs:sequence>
                    <xs:element name="paisaje" type="xs:string" maxOccurs="unbounded"/>
                  </xs:sequence>
                  </xs:complexType>
                </xs:element>
                <xs:element name="poblacion" type="xs:number" maxOccurs="unbounded"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          </xs:complexType>
          <xs:attribute name="nombre"/>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== angeldzz/PrimerCursoDAW/Lenguaje/3_Trimestre_LM/XML/EjercicioXSD_paises.xml
<?xml version="1.0" encoding="UTF-8"?>
<paises xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicioXSD_paises.xsd">
    <pais nombre="Etiopía">
        <comida_tipica tipo="Pan">Injera</comida_tipica>
        <comida_tipica tipo="Estofado">Doro Wat</comida_tipica>
        <comida_tipica tipo="Bebida">Tej</comida_tipica>
        <region>
            <nombre>África Oriental</nombre>
            <paisajes>
                <paisaje>Montañas Simien</paisaje>
                <paisaje>Lago Tana</paisaje>
            </paisajes>
            <poblacion>109000000</poblacion>
        </region>
    </pais>
    <pais nombre="Nigeria">
        <comida_tipica tipo="Arroz">Jollof Rice</comida_tipica>
        <comida_tipica tipo="Brocheta">Suya</comida_tipica>
        <region>
            <nombre>África Occidental</nombre>
            <paisajes>
                <paisaje>Delta del Níger</paisaje>
                <paisaje>Montañas Jos</paisaje>
            </paisajes>
            <poblacion>206000000</poblacion>
        </region>
    </pais>
    <pais nombre="Kenia">
        <comida_tipica tipo="Papilla">Ugali</comida_tipica>
        <comida_tipica tipo="Asado">Nyama Choma</comida_tipica>
        <region>
            <nombre>África Oriental</nombre>
            <paisajes>
                <paisaje>Parque Nacional de Masái Mara</paisaje>
                <paisaje>Lago Nakuru</paisaje>
            </paisajes>
            <poblacion>53700000</poblacion>
        </region>
    </pais>
</paises>
