=== angeldzz/PrimerCursoDAW/Lenguaje/3_Trimestre_LM/XML/Tarea_12_restriccionesAtributos_22-04.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="conflictos_internacionales">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="conflicto" maxOccurs="100">
          <xs:complexType>
            <xs:sequence>
            <xs:element name="nombre">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:string">
                    <xs:attribute name="en_curso">
                      <xs:simpleType>
                        <xs:restriction>
                          <xs:enumeration value="true"/>
                          <xs:enumeration value="false"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:attribute>
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
              <xs:element name="victimas" type="xs:integer"/>
              <xs:element name="informacion">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="paises_involucrados">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="pais" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="fuerza" use="required">
                                    <xs:simpleType>
                                      <xs:restriction base="xs:string">
                                        <xs:enumeration value="alta"/>
                                        <xs:enumeration value="media"/>
                                        <xs:enumeration value="baja"/>
                                      </xs:restriction>
                                    </xs:simpleType>
                                  </xs:attribute>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="causas_principales">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="causa" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="tipo" use="required">
                                    <xs:simpleType>
                                      <xs:restriction base="xs:string">
                                        <xs:enumeration value="fuerte"/>
                                        <xs:enumeration value="media"/>
                                        <xs:enumeration value="debil"/>
                                      </xs:restriction>
                                    </xs:simpleType>
                                  </xs:attribute>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="resolucion">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="esfuerzos">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="diplomatico">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="nivel" use="required">
                                          <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                              <xs:minInclusive value="1"/>
                                              <xs:maxInclusive value="9"/>
                                            </xs:restriction>
                                          </xs:simpleType>
                                        </xs:attribute>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="militar">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="nivel" use="required">
                                          <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                              <xs:minInclusive value="1"/>
                                              <xs:maxInclusive value="9"/>
                                            </xs:restriction>
                                          </xs:simpleType>
                                        </xs:attribute>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="acuerdo_paz" type="xs:boolean" use="required"/>
                        <xs:attribute name="alto_al_fuego" type="xs:boolean" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="clave_conflicto" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                      <xs:extension base="xs:string">
                      <xs:attribute name="clave">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Z][1-9][a-z][1-9]"/>
                          </xs:restriction>
                        </xs:simpleType>
                     </xs:attribute>
                </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:integer">
                  <xs:minInclusive value="1"/>
                  <xs:maxInclusive value="100"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== angeldzz/PrimerCursoDAW/Lenguaje/3_Trimestre_LM/XML/Tarea_12_restriccionesAtributos_22-04.xml
<?xml version="1.0" encoding="UTF-8"?>
<conflictos_internacionales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="Tarea_12_restriccionesAtributos_22-04.xsd">
    <conflicto id="1">
        <nombre en_curso="true">Guerra en Oriente Medio</nombre>
        <victimas>10000</victimas>
        <informacion>
            <paises_involucrados>
                <pais fuerza="alta">Israel
                </pais>
                <pais fuerza="baja">Palestina
                </pais>
            </paises_involucrados>
            <causas_principales>
                <causa tipo="fuerte">disputa territorial</causa>
                <causa tipo="debil">conflicto_religioso</causa>
            </causas_principales>
            <resolucion acuerdo_paz="false" alto_al_fuego="true">
                <esfuerzos>
                    <diplomatico nivel="1">Naciones Unidas</diplomatico>
                    <militar nivel="3">OTAN</militar>
                </esfuerzos>
            </resolucion>
        </informacion>
        <clave_conflicto clave="C5D9">inactiva</clave_conflicto>
        <clave_conflicto clave="D6Y8">activa</clave_conflicto>
    </conflicto>
    <conflicto id="2">
        <nombre en_curso="true">Conflicto en Sudán</nombre>
        <victimas>15000</victimas>
        <informacion>
            <paises_involucrados>
                <pais fuerza="alta">Sudán
                </pais>
                <pais fuerza="media">Sudán del Sur
                </pais>
            </paises_involucrados>
            <causas_principales>
                <causa tipo="fuerte">injerencia extranjera</causa>
                <causa tipo="media">conflicto territorial</causa>
                <causa tipo="debil">conflicto étnico</causa>
            </causas_principales>
            <resolucion acuerdo_paz="false" alto_al_fuego="false">
                <esfuerzos>
                    <diplomatico nivel="2">Unión Africana</diplomatico>
                    <militar nivel="1">ONU</militar>
                </esfuerzos>
            </resolucion>
        </informacion>
        <clave_conflicto clave="A3T8">activa</clave_conflicto>
    </conflicto>
</conflictos_internacionales>
