=== angeldzz/PrimerCursoDAW/Lenguaje/RepasoLenguaje/Ejercicio_Repaso.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="personas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="nacimiento">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia" type="xs:string" />
                                        <xs:element name="Mes" type="xs:string" />
                                        <xs:element name="Año" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Dirección">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Calle" type="xs:string" />
                                        <xs:element name="Provincia" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="CP" type="xs:integer" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="sexo" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== angeldzz/PrimerCursoDAW/Lenguaje/RepasoLenguaje/Ejercicio_Repaso.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
<!DOCTYPE personas [
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre,nacimiento,Dirección)>
<!ATTLIST persona sexo NMTOKEN #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nacimiento (dia,Mes,Año)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT Mes (#PCDATA)>
<!ELEMENT Año (#PCDATA)>
<!ELEMENT Dirección (Calle,Provincia)>
<!ATTLIST Dirección CP NMTOKEN #REQUIRED>
<!ELEMENT Calle (#PCDATA)>
<!ELEMENT Provincia (#PCDATA)>
]> 
-->
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Ejercicio_Repaso.xsd">
    <persona sexo="Mujer">
        <nombre>María Fernández</nombre>
        <nacimiento>
            <dia>01</dia>
            <Mes>Junio</Mes>
            <Año>1975</Año>
        </nacimiento>
        <Dirección CP="28731">
            <Calle>C/ Álcala</Calle>
            <Provincia>Madrid</Provincia>
        </Dirección>
    </persona>
    <persona sexo="Hombre">
        <nombre>Juan Jiménez</nombre>
        <nacimiento>
            <dia>09</dia>
            <Mes>Febrero</Mes>
            <Año>1990</Año>
        </nacimiento>
        <Dirección CP="28001">
            <Calle>C/ Amatista</Calle>
            <Provincia>Madrid</Provincia>
        </Dirección>
    </persona>
</personas>
