=== angeldzz/PrimerCursoDAW/Lenguaje/RepasoLenguaje/Repaso.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empleados">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="nacimiento" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia" type="xs:string" />
                                        <xs:element name="mes" type="xs:string" />
                                        <xs:element name="aÃ±o" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="direccion" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="calle" type="xs:string" />
                                        <xs:element name="provincia" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="CP" type="xs:integer" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="sexo" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== angeldzz/PrimerCursoDAW/Lenguaje/RepasoLenguaje/Repaso.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE empleados [
    <!ELEMENT empleados (persona+)>
    <!ELEMENT persona (nombre+,nacimiento?,direccion*)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT nacimiento (dia,mes,año)>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT año (#PCDATA)>
    <!ELEMENT direccion (calle,provincia)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT provincia (#PCDATA)>
    <!ATTLIST persona sexo CDATA #REQUIRED>
    <!ATTLIST direccion CP CDATA #REQUIRED>
]> -->
<empleados xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Repaso.xsd">
    <persona sexo="Mujer">
        <nombre>María Fernández</nombre>
        <nacimiento>
            <dia>01</dia>
            <mes>Junio</mes>
            <año>1973</año>
        </nacimiento>
        <direccion CP="28731">
            <calle>C/Álcala</calle>
            <provincia>Madrid</provincia>
        </direccion>
    </persona>
    <persona sexo="Hombre">
        <nombre>Juan Jiménez</nombre>
        <nacimiento>
            <dia>09</dia>
            <mes>Febrero</mes>
            <año>1990</año>
        </nacimiento>
        <direccion CP="28001">
            <calle>C/ Amatista</calle>
            <provincia>Madrid</provincia>
        </direccion>
    </persona>
    <persona sexo="Mujer">
        <nombre>Rosa García</nombre>
        <direccion CP="28003">
            <calle>C/Huerta</calle>
            <provincia>Madrid</provincia>
        </direccion>
        <direccion CP="45006">
            <calle>C/Asturias</calle>
            <provincia>Toledo</provincia>
        </direccion>
    </persona>
</empleados>
